Repository FS-part4-1team-FitMate/FitMate-FE, pull requests merged in 2025-01, with the labels that each got.

#3 [서유림] Docs: PR 템플릿 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 완료

#6 [서유림] Feat: 드롭다운
  package-lock.json
  package.json
  postcss.config.js
  public/assets/ic/ic_arrow-down_md-36x36.svg
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownList.tsx
  src/components/Dropdown/DropdownMenu.tsx
  src/pages/index.tsx
  src/types/dropdown.ts
  tailwind.config.js
  tsconfig.json
Labels: 완료

#13 [서유림] Feat: 검색
  src/assets/ic/Ic_search_sm.svg
  src/assets/ic/ic_search_md.svg
  src/components/Common/Search.tsx
  src/imageExports.ts
  src/styles/globals.css
Labels: 완료

#12 [천우승] Feat: 채팅 컴포넌트 추가
  package-lock.json
  package.json
  src/components/ChatBubble.tsx
  src/lib/api/requestService.ts
  src/pages/user/create-request.tsx
Labels: 완료

#11 [이강수] Feat: login/signup #4
  src/components/GNB.tsx
  src/components/ImageUploader.tsx
  src/components/SignUpForm.tsx
  src/lib/api/authService.ts
  src/pages/login.tsx
  src/pages/trainer/[trainerId]/profile/regist.tsx
  src/pages/trainer/signup.tsx
  src/pages/user/profile/regist.tsx
  src/pages/user/signup.tsx
  src/types/types.ts
Labels: 완료

#15 [서유림] Feat: 카드템플릿
  src/components/Cards/FindTrainerCard.tsx
  src/components/Cards/PendingLessonCard.tsx
  src/components/Cards/QuoteCard.tsx
  src/components/Cards/RequestLessonCard.tsx
  src/components/Common/Card/CardContainer.tsx
  src/components/Common/Card/LessonInfo.tsx
  src/components/Common/Card/Line.tsx
  src/components/Common/Card/QuotePrice.tsx
  src/components/Common/Card/TrainerInfo/Experience.tsx
  src/components/Common/Card/TrainerInfo/Favorite.tsx
  src/components/Common/Card/TrainerInfo/LessonCount.tsx
  src/components/Common/Card/TrainerInfo/Rating.tsx
  src/components/Common/Card/TrainerInfo/TrainerInfo.tsx
Labels: 완료

#17 [서유림] Feat: Tab 컴포넌트
  src/components/Tab.tsx
  src/pages/_app.tsx
  src/pages/user/my-lesson/active-lesson/index.tsx
Labels: 완료

#20 [서유림] Design: 랜딩 페이지
  src/pages/index.tsx
  tailwind.config.js
Labels: 완료

#16 [천우승] Feat: 견적 요청하기
  global.d.ts
  package-lock.json
  package.json
  src/components/ChatBubble.tsx
  src/lib/api/requestService.ts
  src/pages/_document.tsx
  src/pages/user/create-request.tsx
  src/styles/globals.css
  tsconfig.json
Labels: 완료

#24 [서유림] Feat: 강사님 찾기 페이지 UI
  src/components/Cards/FindTrainerCard.tsx
  src/components/Common/Card/CardContainer.tsx
  src/components/Common/Card/TrainerInfo/Experience.tsx
  src/components/Common/Card/TrainerInfo/Favorite.tsx
  src/components/Common/Card/TrainerInfo/LessonCount.tsx
  src/components/Common/Card/TrainerInfo/Rating.tsx
  src/components/Common/Card/TrainerInfo/TrainerInfo.tsx
  src/components/Common/Title.tsx
  src/components/Dropdown/DropdownList.tsx
  src/components/Dropdown/DropdownMenu.tsx
  src/components/FindTrainer/FavoriteTrainer.tsx
  src/components/FindTrainer/Filter.tsx
  src/pages/user/find-trainer.tsx
Labels: 완료, UI 구현

#27 [서유림] Design: SNS 공유 컴포넌트 UI 구현
  src/components/Common/ShareSNS.tsx
Labels: 완료, UI 구현

#28 [서유림] Design: 강사님 상세 페이지 UI
  src/components/Cards/RequestLessonCard.tsx
  src/components/Common/Card/Line.tsx
  src/components/Common/Card/TrainerInfo/TrainerInfo.tsx
  src/pages/user/detail-trainer/[trainerId].tsx
Labels: 완료, UI 구현

#29 [서유림] Design: 대기중인 요청 페이지 UI 구현
  src/components/Cards/PendingLessonCard.tsx
  src/pages/_app.tsx
  src/pages/user/my-lesson/pending-request/index.tsx
Labels: 완료, UI 구현

#26 [천우승] Feat: 찜한 강사님
  src/components/Cards/FavoriteTrainerCard.tsx
  src/components/CreateRequest/ChatBubble.tsx
  src/components/CreateRequest/ProgressBar.tsx
  src/lib/api/userService.ts
  src/pages/user/create-request.tsx
  src/pages/user/liked-trainer.tsx
Labels: 완료

#30 [서유림] Feat: 대기중인 요청 상세 페이지 UI
  src/components/Common/QuoteInfo.tsx
  src/components/Tab.tsx
  src/pages/user/my-lesson/pending-request/[id].tsx
  src/pages/user/my-lesson/pending-request/index.tsx
Labels: 완료, UI 구현

#32 [서유림] Feat: 받았던 레슨 페이지 UI
  src/components/Cards/PastLessonCard.tsx
  src/components/Cards/QuoteCard.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownList.tsx
  src/components/Dropdown/DropdownMenu.tsx
  src/pages/user/my-lesson/past-lesson/index.tsx
  src/types/dropdown.ts
Labels: 완료, UI 구현

#33 [서유림] Feat: 받았던 레슨 상세페이지 UI 구현
  src/components/Cards/RequestLessonCard.tsx
  src/components/Common/Card/LessonInfo.tsx
  src/components/Common/Card/TrainerInfo/TrainerInfo.tsx
  src/components/Common/Line.tsx
  src/pages/user/detail-trainer/[trainerId].tsx
  src/pages/user/my-lesson/past-lesson/[id].tsx
  src/pages/user/my-lesson/pending-request/[id].tsx
Labels: 완료, UI 구현

#34 [서유림] Feat: 받은 요청 페이지 UI
  src/components/Cards/RequestLessonCard.tsx
  src/components/CheckboxFilter.tsx
  src/components/FindTrainer/FilterTrainer.tsx
  src/pages/trainer/received-request.tsx
  src/pages/user/find-trainer.tsx
  src/types/dropdown.ts
Labels: 완료, UI 구현

#36 [서유림] Feat: 진행중인 레슨 페이지 UI 구현
  src/components/ActiveLesson/ActiveEmpty.tsx
  src/components/ActiveLesson/ActiveLessonSection.tsx
  src/components/Cards/ActiveLessonCard.tsx
  src/pages/user/my-lesson/active-lesson/index.tsx
Labels: 완료, UI 구현

#35 [이강수] Feat: login/signup
  README.md
  public/favicon.svg
  src/components/GNB.tsx
  src/components/Profile/Regions.tsx
  src/components/SignUp/ImageUploader.tsx
  src/components/SignUp/SignUpForm.tsx
  src/lib/api/authService.ts
  src/pages/_document.tsx
  src/pages/trainer/[trainerId]/account-edit.tsx
  src/pages/trainer/[trainerId]/profile/edit.tsx
  src/pages/trainer/[trainerId]/profile/index.tsx
  src/pages/trainer/[trainerId]/profile/regist.tsx
  src/pages/user/profile/edit.tsx
  src/pages/user/profile/regist.tsx
  src/types/types.ts
Labels: 완료

#38 [서유림] Feat: 견적보내기 모달 UI
  src/components/Cards/RequestLessonCard.tsx
  src/components/Modal/ModalContainer.tsx
  src/components/Modal/SendQuote.tsx
  src/pages/trainer/received-request.tsx
Labels: 완료, UI 구현

#39 [서유림] Feat: 반려요청 모달
  src/components/Cards/RequestLessonCard.tsx
  src/components/CheckboxFilter.tsx
  src/components/Modal/ModalContainer.tsx
  src/components/Modal/RejectedRequest.tsx
Labels: 완료, UI 구현

#40 [이강수] Feat: trainer my page and Refactoring profile edit/regist
  src/components/Cards/ReviewCard.tsx
  src/components/Common/Button.tsx
  src/components/Common/Card/TrainerInfo/Rating.tsx
  src/components/Common/Input.tsx
  src/components/Common/InputPassword.tsx
  src/components/Common/Textarea.tsx
  src/components/Profile/Regions.tsx
  src/components/SignUp/SignUpForm.tsx
  src/lib/api/authService.ts
  src/pages/trainer/[trainerId]/profile/edit.tsx
  src/pages/trainer/[trainerId]/profile/index.tsx
  src/pages/trainer/[trainerId]/profile/regist.tsx
  src/pages/user/profile/edit.tsx
  src/pages/user/profile/regist.tsx
  src/types/constants.ts
  src/types/types.ts
Labels: 완료

#42 [이강수] Feat: trainer my page
  src/components/Cards/RatingAvgCard.tsx
  src/components/Cards/RatingStatCard.tsx
  src/components/Cards/ReviewCard.tsx
  src/pages/trainer/[trainerId]/profile/index.tsx
Labels: 완료

#44 [이강수] Feat: Chip components
  src/components/Chip/ChipLessonType.tsx
  src/components/Chip/ChipRegion.tsx
  src/components/Chip/ChipRequest.tsx
  src/components/Chip/ChipRequestStatus.tsx
  src/components/GNB/GNB.tsx
  src/pages/_app.tsx
  src/pages/chip-test.tsx
  src/types/types.ts
Labels: 완료

#46 [천우승]Feat: 내가 보낸 견적
  src/components/Cards/SentRequestCard.tsx
  src/lib/api/requestService.ts
  src/pages/trainer/managing-request/sent-request.jsx/index.tsx
Labels: 완료

#43 [서유림] Feat: 컴포넌트 반응형
  src/components/ActiveLesson/ActiveLessonSection.tsx
  src/components/Cards/ActiveLessonCard.tsx
  src/components/Cards/FavoriteTrainerCard.tsx
  src/components/Cards/FindTrainerCard.tsx
  src/components/Cards/PastLessonCard.tsx
  src/components/Cards/PendingLessonCard.tsx
  src/components/Cards/QuoteCard.tsx
  src/components/Cards/RequestLessonCard.tsx
  src/components/CheckboxFilter.tsx
  src/components/Common/Card/CardContainer.tsx
  src/components/Common/Card/LessonInfo.tsx
  src/components/Common/Card/QuotePrice.tsx
  src/components/Common/Card/TrainerInfo/Experience.tsx
  src/components/Common/Card/TrainerInfo/Favorite.tsx
  src/components/Common/Card/TrainerInfo/LessonCount.tsx
  src/components/Common/Card/TrainerInfo/Rating.tsx
  src/components/Common/Card/TrainerInfo/TrainerInfo.tsx
  src/components/Common/QuoteInfo.tsx
  src/components/Common/Search.tsx
  src/components/Common/ShareSNS.tsx
  src/components/Common/Title.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownList.tsx
  src/components/Dropdown/DropdownMenu.tsx
  src/components/FindTrainer/FavoriteTrainer.tsx
  src/components/FindTrainer/FilterTrainer.tsx
  src/components/Modal/MobileFilter.tsx
  src/components/Modal/ModalContainer.tsx
  src/components/Modal/RejectedRequest.tsx
  src/components/Modal/SendQuote.tsx
  src/components/Tab.tsx
  src/pages/_document.tsx
Labels: 완료, UI 구현

#52 [서유림] Feat: 칩 컴포넌트 생성
  src/components/Chip/ChipDefault.tsx
  tailwind.config.js
Labels: 완료, UI 구현

#48 [서유림] Feat: 페이지 반응형
  src/components/ActiveLesson/ActiveLessonSection.tsx
  src/components/Cards/ActiveLessonCard.tsx
  src/components/Cards/FindTrainerCard.tsx
  src/components/Cards/PastLessonCard.tsx
  src/components/Cards/PendingLessonCard.tsx
  src/components/Cards/QuoteCard.tsx
  src/components/Cards/RequestLessonCard.tsx
  src/components/CheckboxFilter.tsx
  src/components/Common/Card/CardContainer.tsx
  src/components/Common/Card/LessonInfo.tsx
  src/components/Common/Card/QuotePrice.tsx
  src/components/Common/Card/TrainerInfo/TrainerInfo.tsx
  src/components/Common/QuoteInfo.tsx
  src/components/Common/Search.tsx
  src/components/Common/ShareSNS.tsx
  src/components/Common/Title.tsx
  src/components/Dropdown/DropdownList.tsx
  src/components/Dropdown/DropdownMenu.tsx
  src/components/FindTrainer/FavoriteTrainer.tsx
  src/components/Modal/RejectedRequest.tsx
  src/components/Modal/SendQuote.tsx
  src/pages/index.tsx
  src/pages/trainer/received-request.tsx
  src/pages/user/detail-trainer/[trainerId].tsx
  src/pages/user/find-trainer.tsx
  src/pages/user/my-lesson/active-lesson/index.tsx
  src/pages/user/my-lesson/past-lesson/[id].tsx
  src/pages/user/my-lesson/past-lesson/index.tsx
  src/pages/user/my-lesson/pending-request/[id].tsx
  src/pages/user/my-lesson/pending-request/index.tsx
Labels: 완료, UI 구현

#49 [천우승] Feat: 견적 상세 페이지
  src/pages/trainer/managing-request/sent-request.jsx/[id].tsx
Labels: 완료, UI 구현

#56 [서유림] Feat: 받은 요청 페이지 기능 구현
  mock/received-request.json
  src/components/Cards/RequestLessonCard.tsx
  src/components/CheckboxFilter.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Modal/MobileFilter.tsx
  src/lib/api/lessonService.ts
  src/lib/api/method.ts
  src/lib/api/quoteService.ts
  src/lib/utils/formatDate.ts
  src/lib/utils/formatTime.ts
  src/pages/trainer/received-request.tsx
  src/types/dropdown.ts
  src/types/lesson.ts
  src/types/quote.ts
  src/types/types.ts
Labels: 완료, 기능 구현

#57 [천우승] Feat: 작성가능한 리뷰 페이지
  src/components/Cards/writeReviewCard.tsx
  src/components/Common/Textarea.tsx
  src/components/Modal/ModalContainer.tsx
  src/components/Modal/ReviewModal.tsx
  src/lib/api/ReviewService.ts
  src/pages/user/lesson-review/awaiting-review.tsx
Labels: 완료, 기능 구현

#60 [서유림] Feat: 견적 보내기 기능
  src/components/Cards/RequestLessonCard.tsx
  src/components/Cards/UserCard.tsx
  src/components/Modal/ModalContainer.tsx
  src/components/Modal/SendQuote.tsx
  src/hooks/useQuoteValidate.ts
  src/lib/api/method.ts
  src/lib/api/quoteService.ts
  src/types/quote.ts
Labels: 완료, 기능 구현

#58 [이강수] Feat: 로그인 시 프로필 등록 페이지로 보낼지 기본 페이지로 보낼지...
  src/components/GNB/GNB.tsx
  src/pages/login.tsx
  src/pages/trainer/[trainerId]/profile/edit.tsx
  src/pages/trainer/[trainerId]/profile/index.tsx
  src/pages/trainer/[trainerId]/profile/regist.tsx
  src/pages/user/profile/edit.tsx
Labels: 완료

#62 [서유림] Feat: 견적 상세 페이지 기능 구현
  src/components/Cards/FindTrainerCard.tsx
  src/components/Common/QuoteInfo.tsx
  src/lib/api/lessonService.ts
  src/lib/utils/formatPrice.ts
  src/pages/user/my-lesson/past-lesson/[id].tsx
  src/pages/user/my-lesson/pending-request/[id].tsx
  src/types/quote.ts
Labels: 완료, 기능 구현

#65 [이강수] Feat: 로그인/가입하기/프로필 전반적으로 수정.
  .prettierrc
  package-lock.json
  package.json
  src/components/Common/Input.tsx
  src/components/GNB/GNB.tsx
  src/components/SignUp/ImageUploader.tsx
  src/components/SignUp/SignUpForm.tsx
  src/contexts/UserProvider.tsx
  src/lib/api/authService.ts
  src/pages/login.tsx
  src/pages/trainer/[trainerId]/profile/edit.tsx
  src/pages/trainer/[trainerId]/profile/index.tsx
  src/pages/trainer/[trainerId]/profile/regist.tsx
  src/pages/user/profile/edit.tsx
  src/pages/user/profile/index.tsx
  src/pages/user/profile/regist.tsx
  src/types/constants.ts
  src/types/types.ts
  tsconfig.json
Labels: 완료

#67 [서유림] Feat: 받은요청 페이지 기능 구현
  package-lock.json
  package.json
  src/components/Cards/RequestLessonCard.tsx
  src/components/CheckboxFilter.tsx
  src/components/Common/Search.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Modal/MobileFilter.tsx
  src/pages/trainer/received-request.tsx
  src/types/dropdown.ts
  src/types/lesson.ts
Labels: 완료, 기능 구현

#68 [서유림] Feat: 강사님찾기 api연결
  src/components/Cards/FindTrainerCard.tsx
  src/components/CheckboxFilter.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownList.tsx
  src/components/Dropdown/DropdownMenu.tsx
  src/components/FindTrainer/FavoriteTrainer.tsx
  src/components/FindTrainer/FilterTrainer.tsx
  src/lib/api/trainerService.ts
  src/pages/user/find-trainer.tsx
  src/types/dropdown.ts
  src/types/trainer.ts
Labels: 완료, 기능 구현

#72 [서유림] Feat: 견적상세
  src/components/Common/QuoteInfo.tsx
  src/lib/utils/formatDateTime.ts
  src/lib/utils/formatPrice.ts
  src/pages/user/my-lesson/pending-request/[quoteId].tsx
Labels: 완료, 기능 구현

#69 [서유림] Feat: 견적 모달
  src/components/Cards/RequestLessonCard.tsx
  src/components/Cards/UserCard.tsx
  src/components/Modal/RejectedRequest.tsx
  src/components/Modal/SendQuote.tsx
  src/hooks/useQuoteValidate.ts
  src/lib/api/lessonService.ts
  src/types/lesson.ts
  src/types/quote.ts
Labels: 완료, 기능 구현

#70 [이강수] Feat SNS 로그인/가입하기
  src/components/Common/Favorite.tsx
  src/components/GNB/GNB.tsx
  src/components/SignUp/SignUpForm.tsx
  src/lib/api/ReviewService.ts
  src/lib/api/authService.ts
  src/lib/api/userService.ts
  src/pages/login.tsx
  src/pages/sns-login.tsx
  src/pages/trainer/[trainerId]/profile/edit.tsx
  src/pages/trainer/[trainerId]/profile/index.tsx
  src/pages/trainer/[trainerId]/profile/regist.tsx
  src/pages/user/profile/edit.tsx
  src/pages/user/profile/index.tsx
  src/pages/user/profile/regist.tsx
Labels: 완료

#73 [서유림] Feat: 받은 요청 수정
  package-lock.json
  package.json
  src/components/Cards/RequestLessonCard.tsx
  src/components/CheckboxFilter.tsx
  src/components/Common/Card/LessonInfo.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownList.tsx
  src/components/Modal/MobileFilter.tsx
  src/components/ReceivedRequest/LessonFilter.tsx
  src/components/ReceivedRequest/ListHeader.tsx
  src/lib/api/lessonService.ts
  src/pages/trainer/received-request.tsx
  src/types/dropdown.ts
  src/types/lesson.ts
  tailwind.config.js
Labels: 완료, 기능 구현

#75 [서유림] Feat: 내 레슨 관리
  src/components/ActiveLesson/ActiveLessonSection.tsx
  src/components/Cards/ActiveLessonCard.tsx
  src/components/Cards/PastLessonCard.tsx
  src/components/Cards/PendingLessonCard.tsx
  src/components/Cards/QuoteCard.tsx
  src/components/Chip/ChipLessonType.tsx
  src/components/Common/Card/CardContainer.tsx
  src/components/Common/Card/LessonInfo.tsx
  src/components/Common/Card/QuotePrice.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/FindTrainer/FilterTrainer.tsx
  src/components/Modal/ModalContainer.tsx
  src/lib/api/quoteService.ts
  src/pages/user/my-lesson/active-lesson/index.tsx
  src/pages/user/my-lesson/past-lesson/index.tsx
  src/pages/user/my-lesson/pending-request/index.tsx
  src/types/dropdown.ts
  src/types/lesson.ts
  src/types/quote.ts
  src/types/trainer.ts
Labels: 완료, 진행중

#76 [서유림] Design: UI 수정
  src/pages/user/my-lesson/pending-request/index.tsx
Labels: 완료, UI 구현

#77 [서유림] Fix: 데이터 반환 조건문 수정
  src/components/Cards/FindTrainerCard.tsx
  src/components/Cards/UserCard.tsx
  src/components/DetailTrainer/TrainerControl.tsx
  src/components/Modal/SendQuote.tsx
  src/pages/user/detail-trainer/[trainerId].tsx
  src/pages/user/find-trainer.tsx
  src/pages/user/my-lesson/past-lesson/index.tsx
  src/pages/user/my-lesson/pending-request/index.tsx
Labels: 완료, 기능 구현

#78 [이강수] Feat Favorite
  src/components/Common/Favorite.tsx
  src/lib/api/ReviewService.ts
  src/lib/api/userService.ts
  src/pages/login.tsx
  src/pages/sns-login.tsx
  src/pages/trainer/[trainerId]/profile/index.tsx
Labels: 완료

#79 [서유림] Feat: 좋아요 데이터 연결
  src/components/Cards/FavoriteTrainerCard.tsx
  src/components/Cards/FindTrainerCard.tsx
  src/components/Cards/PastLessonCard.tsx
  src/components/Cards/PendingLessonCard.tsx
  src/components/Cards/QuoteCard.tsx
  src/components/Common/Card/TrainerInfo/Rating.tsx
  src/components/Common/Card/TrainerInfo/TrainerInfo.tsx
  src/components/Common/Favorite.tsx
  src/components/DetailTrainer/TrainerControl.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownList.tsx
  src/components/FindTrainer/FavoriteTrainer.tsx
  src/lib/api/lessonService.ts
  src/pages/user/detail-trainer/[trainerId].tsx
  src/pages/user/find-trainer.tsx
  src/types/trainer.ts
Labels: 완료, 기능 구현

#80 [이강수] Refactoring GNB.tsx
  src/components/Cards/RatingStatCard.tsx
  src/components/Common/Pagination.tsx
  src/components/GNB/GNB.tsx
  src/lib/api/ReviewService.ts
  src/pages/trainer/[trainerId]/profile/index.tsx
  src/types/reviews.ts
Labels: 완료
