Repository FS-part4-1team-FitMate/FitMate-FE, pull requests merged in 2025-02, with the labels that each got.

#81 [서유림] Feat: 내 레슨 관리 수정
  src/components/ActiveLesson/ActiveLessonSection.tsx
  src/components/Cards/ActiveLessonCard.tsx
  src/components/Cards/PastLessonCard.tsx
  src/lib/api/lessonService.ts
  src/pages/user/my-lesson/active-lesson/index.tsx
  src/pages/user/my-lesson/past-lesson/index.tsx
  src/pages/user/my-lesson/pending-request/index.tsx
Labels: 완료, 기능 구현

#82 [서유림] Feat: sns 공유
  global.d.ts
  src/components/Cards/FindTrainerCard.tsx
  src/components/Common/ShareSNS.tsx
  src/components/DetailTrainer/TrainerInfo.tsx
  src/pages/_document.tsx
  src/pages/trainer/managing-request/sent-request.jsx/[id].tsx
  src/pages/user/detail-trainer/[trainerId].tsx
  src/pages/user/my-lesson/past-lesson/[quoteId].tsx
  src/pages/user/my-lesson/pending-request/[quoteId].tsx
  src/types/trainer.ts
Labels: 완료, 기능 구현

#84 [이강수] Feat: Linting error and npm run build error handled
  Dockerfile
  global.d.ts
  package-lock.json
  package.json
  src/components/Cards/RejectedRequestCard.tsx
  src/components/Cards/SentRequestCard.tsx
  src/components/Cards/writeReviewCard.tsx
  src/components/Common/Card/LessonInfo.tsx
  src/components/Common/Card/TrainerInfo/TrainerInfo.tsx
  src/components/DetailTrainer/TrainerControl.tsx
  src/components/DetailTrainer/TrainerReview.tsx
  src/components/Modal/ReviewModal.tsx
  src/lib/api/ReviewService.ts
  src/pages/login.tsx
  src/pages/trainer/[trainerId]/profile/edit.tsx
  src/pages/trainer/[trainerId]/profile/index.tsx
  src/pages/trainer/managing-request/sent-request/[id].tsx
  src/pages/trainer/managing-request/sent-request/index.tsx
  src/pages/user/create-request.tsx
  src/pages/user/lesson-review/awaiting-review.tsx
  src/pages/user/lesson-review/written-review.tsx
  src/pages/user/profile/edit.tsx
  src/types/quote.ts
  src/types/reviews.ts
  tsconfig.json
Labels: 완료

#83 [서유림] Feat: 리뷰 차트 수정
  src/components/Cards/ReviewCard.tsx
  src/components/DetailTrainer/TrainerControl.tsx
  src/components/DetailTrainer/TrainerReview.tsx
  src/pages/_app.tsx
  src/pages/user/detail-trainer/[trainerId].tsx
  src/types/reviews.ts
Labels: 완료, 기능 구현

#85 [서유림] Feat: 에러 처리
  package-lock.json
  package.json
  src/components/Cards/ActiveLessonCard.tsx
  src/components/Cards/FavoriteTrainerCard.tsx
  src/components/Cards/PastLessonCard.tsx
  src/components/Cards/PendingLessonCard.tsx
  src/components/Cards/QuoteCard.tsx
  src/components/Cards/RatingStatCard.tsx
  src/components/Cards/RequestLessonCard.tsx
  src/components/Common/QuoteInfo.tsx
  src/components/Common/ShareSNS.tsx
  src/components/DetailTrainer/TrainerControl.tsx
  src/components/DetailTrainer/TrainerReview.tsx
  src/components/FindTrainer/FavoriteTrainer.tsx
  src/pages/_app.tsx
  src/pages/trainer/received-request.tsx
  src/pages/user/detail-trainer/[trainerId].tsx
  src/pages/user/find-trainer.tsx
  src/pages/user/my-lesson/active-lesson/index.tsx
  src/pages/user/my-lesson/past-lesson/[quoteId].tsx
  src/pages/user/my-lesson/past-lesson/index.tsx
  src/pages/user/my-lesson/pending-request/[quoteId].tsx
  src/pages/user/my-lesson/pending-request/index.tsx
  src/types/dropdown.ts
Labels: 완료, 기능 구현

#90 [서유림] Feat: 코드 리팩토링
  src/components/ActiveLesson/ActiveLessonSection.tsx
  src/components/Cards/ActiveLessonCard.tsx
  src/components/Cards/FavoriteTrainerCard.tsx
  src/components/Cards/FindTrainerCard.tsx
  src/components/Cards/PastLessonCard.tsx
  src/components/Cards/PendingLessonCard.tsx
  src/components/Cards/QuoteCard.tsx
  src/components/Cards/RequestLessonCard.tsx
  src/components/CheckboxFilter.tsx
  src/components/Common/Card/LessonInfo.tsx
  src/components/Common/QuoteInfo.tsx
  src/components/DetailTrainer/TrainerControl.tsx
  src/components/DetailTrainer/TrainerInfo.tsx
  src/components/DetailTrainer/TrainerReview.tsx
  src/components/FindTrainer/FavoriteTrainer.tsx
  src/components/Modal/MobileFilter.tsx
  src/components/ReceivedRequest/LessonFilter.tsx
  src/components/ReceivedRequest/ListHeader.tsx
  src/lib/api/lessonService.ts
  src/lib/api/queries/lesson.ts
  src/lib/api/queries/quote.ts
  src/lib/api/queries/review.ts
  src/lib/api/queries/trainer.ts
  src/pages/trainer/received-request.tsx
  src/pages/user/detail-trainer/[trainerId].tsx
  src/pages/user/find-trainer.tsx
  src/pages/user/my-lesson/active-lesson/index.tsx
  src/pages/user/my-lesson/past-lesson/[quoteId].tsx
  src/pages/user/my-lesson/past-lesson/index.tsx
  src/pages/user/my-lesson/pending-request/[quoteId].tsx
  src/pages/user/my-lesson/pending-request/index.tsx
  src/types/dropdown.ts
  src/types/lesson.ts
Labels: 완료, 기능 구현

#92 [이강수] Feat: Remembering query params and Notifications and Error handled
  src/components/Cards/FindTrainerCard.tsx
  src/components/Cards/MyReviewCard.tsx
  src/components/Cards/RatingStatCard.tsx
  src/components/Cards/RejectedRequestCard.tsx
  src/components/Cards/SentRequestCard.tsx
  src/components/Common/Card/TrainerInfo/Experience.tsx
  src/components/Common/Card/TrainerInfo/Favorite.tsx
  src/components/Common/Card/TrainerInfo/LessonCount.tsx
  src/components/Common/Card/TrainerInfo/Rating.tsx
  src/components/Common/Card/TrainerInfo/TrainerInfo.tsx
  src/components/Common/Favorite.tsx
  src/components/Common/ShareSNS.tsx
  src/components/DetailTrainer/TrainerControl.tsx
  src/components/DetailTrainer/TrainerInfo.tsx
  src/components/GNB/GNB.tsx
  src/contexts/NotificationProvider.tsx
  src/lib/api/authService.ts
  src/lib/api/notiService.ts
  src/lib/api/queries/notification.ts
  src/lib/api/queries/review.ts
  src/lib/api/queries/trainer.ts
  src/lib/api/queries/user.ts
  src/lib/api/trainerService.ts
  src/lib/api/userService.ts
  src/lib/utils/calcAvgRating.ts
  src/pages/_app.tsx
  src/pages/login.tsx
  src/pages/query-params-test.tsx
  src/pages/trainer/[trainerId]/profile/edit.tsx
  src/pages/trainer/[trainerId]/profile/index.tsx
  src/pages/trainer/[trainerId]/profile/regist.tsx
  src/pages/user/lesson-review/written-review.tsx
  src/pages/user/profile/edit.tsx
  src/pages/user/profile/index.tsx
  src/pages/user/profile/regist.tsx
  src/types/notis.ts
  src/types/trainer.ts
  src/types/types.ts
Labels: 완료

#93 [이강수] Feat: SignUp with Email verification
  src/components/Common/Button.tsx
  src/components/SignUp/SignUpForm.tsx
  src/lib/api/authService.ts
  src/lib/api/notiService.ts
  src/pages/login.tsx
Labels: 완료

#94 [천우승] Feat: 레슨 요청하기 페이지 수정
  src/lib/api/requestService.ts
  src/pages/user/create-request.tsx
  src/pages/user/lesson-review/written-review.tsx
Labels: 완료, 기능 구현

#98 [이강수] Create main.yml (CI/CD), GNB, Notifications
  .github/workflows/main.yml
  src/assets/ic/ic_red_dot.svg
  src/components/GNB/GNB.tsx
  src/components/GNB/LogInButton.tsx
  src/components/GNB/Logo.tsx
  src/components/GNB/Menus.tsx
  src/components/GNB/MyProfileMenus.tsx
  src/components/GNB/Notifications.tsx
  src/contexts/NotificationProvider.tsx
  src/imageExports.ts
  src/lib/api/notiService.ts
  src/lib/api/queries/notification.ts
  src/pages/noti.tsx
  src/types/notis.ts
  src/types/types.ts
Labels: 완료

#101 [이강수] Fix: Initial values :: contexts\NotificationProvider.tsx
  src/contexts/NotificationProvider.tsx
  src/pages/trainer/[trainerId]/profile/edit.tsx
  src/pages/trainer/[trainerId]/profile/regist.tsx
  src/pages/user/profile/edit.tsx
  src/pages/user/profile/regist.tsx
Labels: 완료

#100 [서유림] Feat: UI 수정
  public/favicon.ico
  public/favicon.svg
  src/assets/ic/ic_search_blue.svg
  src/components/ActiveLesson/ActiveEmpty.tsx
  src/components/ActiveLesson/ActiveLessonSection.tsx
  src/components/Cards/ActiveLessonCard.tsx
  src/components/Cards/FavoriteTrainerCard.tsx
  src/components/Cards/FindTrainerCard.tsx
  src/components/Cards/PendingLessonCard.tsx
  src/components/Cards/QuoteCard.tsx
  src/components/Cards/RatingAvgCard.tsx
  src/components/Cards/RatingStatCard.tsx
  src/components/Cards/RejectedRequestCard.tsx
  src/components/Cards/RequestLessonCard.tsx
  src/components/Cards/ReviewCard.tsx
  src/components/Cards/SentRequestCard.tsx
  src/components/CheckboxFilter.tsx
  src/components/Chip/ChipDefault.tsx
  src/components/Chip/ChipLessonType.tsx
  src/components/Chip/ChipRegion.tsx
  src/components/Chip/ChipRequest.tsx
  src/components/Chip/ChipRequestStatus.tsx
  src/components/Common/Card/CardContainer.tsx
  src/components/Common/Card/TrainerInfo/Experience.tsx
  src/components/Common/Card/TrainerInfo/LessonCount.tsx
  src/components/Common/Card/TrainerInfo/Rating.tsx
  src/components/Common/Card/TrainerInfo/TrainerInfo.tsx
  src/components/Common/EmptyLesson.tsx
  src/components/Common/Pagination.tsx
  src/components/Common/QuoteInfo.tsx
  src/components/Common/ShareSNS.tsx
  src/components/Common/StarPoints.tsx
  src/components/DetailTrainer/TrainerControl.tsx
  src/components/DetailTrainer/TrainerInfo.tsx
  src/components/DetailTrainer/TrainerReview.tsx
  src/components/FindTrainer/FavoriteTrainer.tsx
  src/components/Modal/ModalContainer.tsx
  src/components/Modal/RejectedRequest.tsx
  src/components/Modal/SendQuote.tsx
  src/components/ReceivedRequest/LessonFilter.tsx
  src/components/Tab.tsx
  src/lib/api/queries/lesson.ts
  src/lib/api/queries/trainer.ts
  src/lib/utils/formatDateTime.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/chip-test.tsx
  src/pages/trainer/[trainerId]/profile/index.tsx
  src/pages/trainer/received-request.tsx
  src/pages/user/detail-trainer/[trainerId].tsx
  src/pages/user/find-trainer.tsx
  src/pages/user/my-lesson/active-lesson/index.tsx
  src/pages/user/my-lesson/lesson-history/index.tsx
  src/pages/user/my-lesson/past-lesson/[quoteId].tsx
  src/pages/user/my-lesson/past-lesson/index.tsx
  src/pages/user/my-lesson/pending-request/[quoteId].tsx
  src/pages/user/my-lesson/pending-request/index.tsx
  src/types/lesson.ts
  src/types/types.ts
Labels: 완료, UI 구현

#104 Update main.yml
  .github/workflows/main.yml
Labels: 완료

#106 [이강수] Feat: SNS login 실패시 메세지 띄우기
  src/pages/auth/google/redirect.tsx
  src/pages/auth/kakao/redirect.tsx
  src/pages/auth/naver/redirect.tsx
Labels: 완료

#107 [이강수] Update main.yml (CI/CD)
  .github/workflows/main.yml
Labels: 완료

#105 [천우승] Fix: 오류 수정
  src/components/Cards/MyReviewCard.tsx
  src/lib/api/requestService.ts
  src/pages/user/create-request.tsx
Labels: 완료, 기능 구현

#108 [이강수] Update main.yml (CI/CD), and SNS-login fail handled
  .github/workflows/main.yml
  src/pages/login.tsx
  src/pages/query-params-test.tsx
  src/pages/sns-login.tsx
Labels: 완료

#109 [이강수] Update main.yml (CI/CD)
  .github/workflows/main.yml
Labels: 완료

#110 [이강수] Update main.yml (CI/CD), SNS-login JSON.parse error handled
  .github/workflows/main.yml
  src/pages/sns-login.tsx
Labels: 완료

#112 [천우승] Fix: 레슨 요청, 견적 목록, 반려된 견적 수정
  src/components/Cards/SentRequestCard.tsx
  src/lib/api/quoteService.ts
  src/lib/api/requestService.ts
  src/pages/trainer/managing-request/sent-request/[id].tsx
  src/pages/trainer/managing-request/sent-request/index.tsx
  src/pages/user/create-request.tsx
  src/types/types.ts
Labels: 완료, 기능 구현

#103 [서유림] Refactor: UI 수정
  package-lock.json
  src/assets/ic/ic_gender_female.svg
  src/assets/ic/ic_gender_male.svg
  src/components/Common/Input.tsx
  src/components/Common/InputPassword.tsx
  src/components/Common/QuoteInfo.tsx
  src/components/Common/Textarea.tsx
  src/components/GNB/EmptyNotification.tsx
  src/components/GNB/MyProfileMenus.tsx
  src/components/GNB/Notifications.tsx
  src/components/Profile/Regions.tsx
  src/components/SignUp/ImageUploader.tsx
  src/components/SignUp/SignUpForm.tsx
  src/imageExports.ts
  src/pages/login.tsx
  src/pages/noti.tsx
  src/pages/trainer/[trainerId]/profile/edit.tsx
  src/pages/trainer/[trainerId]/profile/index.tsx
  src/pages/trainer/[trainerId]/profile/regist.tsx
  src/pages/user/profile/edit.tsx
  src/pages/user/profile/index.tsx
  src/pages/user/profile/regist.tsx
  src/types/constants.ts
Labels: 완료, UI 구현

#115 [이강수] Feat: (CI/CD) Test, and EmptyNoti, and My profile menu added
  .github/workflows/main.yml
  src/components/GNB/MyProfileMenus.tsx
  src/components/GNB/Notifications.tsx
  src/pages/auth/google/redirect.tsx
  src/pages/auth/kakao/redirect.tsx
  src/pages/auth/naver/redirect.tsx
  src/pages/trainer/[trainerId]/profile/index.tsx
  src/pages/user/profile/index.tsx
Labels: 완료

#114 [천우승] Fix: 견적, 리뷰 및 찜한 강사 기능 수정
  src/components/Cards/MyReviewCard.tsx
  src/components/Cards/RejectedRequestCard.tsx
  src/components/Cards/SentRequestCard.tsx
  src/components/Cards/writeReviewCard.tsx
  src/components/Common/Card/LessonInfo.tsx
  src/lib/api/ReviewService.ts
  src/lib/api/trainerService.ts
  src/lib/api/userService.ts
  src/pages/trainer/managing-request/rejected-request.tsx
  src/pages/trainer/managing-request/sent-request/index.tsx
  src/pages/user/create-request.tsx
  src/pages/user/lesson-review/awaiting-review.tsx
  src/pages/user/lesson-review/written-review.tsx
  src/pages/user/liked-trainer.tsx
  src/types/quote.ts
  src/types/reviews.ts
Labels: 완료, 기능 구현

#118 [이강수] Feat CI/CD, and Error fixed.
  .github/workflows/main.yml
  Dockerfile
  README.md
  src/components/Cards/FavoriteTrainerCard.tsx
  src/components/Cards/LessonSummaryCard.tsx
  src/components/Cards/MyReviewCard.tsx
  src/components/Cards/QuoteSummary.tsx
  src/components/Cards/RejectedRequestCard.tsx
  src/components/Cards/SentRequestCard.tsx
  src/components/Cards/writeReviewCard.tsx
  src/components/Chat/Chatting.tsx
  src/components/Chat/InputField.tsx
  src/components/Chat/MessageContainer.tsx
  src/components/Common/LessonInfo.tsx
  src/components/FindTrainer/FavoriteTrainer.tsx
  src/components/GNB/EmptyNotification.tsx
  src/components/Modal/ModalContainer.tsx
  src/components/Modal/ReviewModal.tsx
  src/lib/api/ReviewService.ts
  src/lib/api/queries/trainer.ts
  src/lib/api/quoteService.ts
  src/lib/api/requestService.ts
  src/lib/api/trainerService.ts
  src/pages/noti.tsx
  src/pages/sns-login.tsx
  src/pages/trainer/managing-request/rejected-request.tsx
  src/pages/trainer/managing-request/sent-request/[id].tsx
  src/pages/trainer/managing-request/sent-request/index.tsx
  src/pages/user/chat/[roomId].tsx
  src/pages/user/chat/index.tsx
  src/pages/user/create-request.tsx
  src/pages/user/lesson-review/awaiting-review.tsx
  src/pages/user/lesson-review/written-review.tsx
  src/pages/user/liked-trainer.tsx
  src/types/lesson.ts
  src/types/quote.ts
  src/types/reviews.ts
Labels: 완료

#123 [이강수] 자잘한 수정 cherry-pick commit by 우승님
  src/components/Cards/SentRequestCard.tsx
  src/pages/trainer/managing-request/sent-request/[id].tsx
Labels: 완료

#120 [서유림] Fix: 오류 수정
  src/components/Cards/ActiveLessonCard.tsx
  src/components/Cards/PendingLessonCard.tsx
  src/components/Cards/QuoteCard.tsx
  src/types/lesson.ts
Labels: 완료

#124 [이강수] Fix: 우승님 PR 복구, and JSON.parse 오류 try/catch
  src/components/Cards/RequestLessonCard.tsx
  src/components/Cards/SentRequestCard.tsx
  src/contexts/UserProvider.tsx
  src/lib/api/instance.ts
  src/pages/login.tsx
  src/pages/trainer/[trainerId]/profile/edit.tsx
  src/pages/trainer/managing-request/sent-request/[id].tsx
Labels: 완료

#121 [천우승] Fix:Error Fix 및 내가 작성한 리뷰 별점 추가
  src/components/Cards/LessonSummaryCard.tsx
  src/components/Cards/MyReviewCard.tsx
  src/components/Modal/ReviewModal.tsx
  src/lib/api/ReviewService.ts
  src/pages/trainer/chat.tsx
  src/types/reviews.ts
Labels: 완료, 기능 구현

#126 [이강수] Feat: GNB background, text color, and duplicate Error handled
  src/components/Common/PopUp.tsx
  src/components/ErrorBoundary.tsx
  src/components/GNB/GNB.tsx
  src/pages/_app.tsx
  src/pages/sns-login.tsx
  src/pages/trainer/managing-request/sent-request/[id].tsx
Labels: 완료

#129 [서유림] Fix: 오류
  src/components/FindTrainer/FavoriteTrainer.tsx
  src/lib/api/queries/trainer.ts
Labels: 완료

#131 [서유림] Feat: 랜딩
  src/assets/ic/ic_fitness.png
  src/assets/ic/ic_rehab.png
  src/assets/ic/ic_sports.png
  src/imageExports.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/user/find-trainer.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: 완료, UI 구현

#132 [서유림] Feat: 404 페이지
  src/assets/img/img_404.svg
  src/imageExports.ts
  src/pages/404.tsx
  src/pages/user/find-trainer.tsx
  src/styles/globals.css
Labels: 완료, UI 구현

#130 [천우승] Fix: UI 수정 및 채팅 기능 수정
  src/components/Cards/MyReviewCard.tsx
  src/components/Cards/QuoteSummary.tsx
  src/components/Cards/writeReviewCard.tsx
  src/components/Chat/ChatList.tsx
  src/components/Chat/ChatRoom.tsx
  src/components/Chat/Chatting.tsx
  src/components/Chat/InputField.tsx
  src/components/Chat/MessageContainer.tsx
  src/components/DetailTrainer/TrainerControl.tsx
  src/components/GNB/Menus.tsx
  src/lib/api/chatService.ts
  src/lib/utils/socket.ts
  src/pages/chat.tsx
  src/pages/trainer/managing-request/rejected-request.tsx
  src/pages/trainer/managing-request/sent-request/[id].tsx
  src/pages/trainer/managing-request/sent-request/index.tsx
  src/pages/user/chat.tsx
  src/pages/user/chat/[roomId].tsx
  src/pages/user/chat/index.tsx
  src/pages/user/lesson-review/awaiting-review.tsx
  src/pages/user/lesson-review/written-review.tsx
  src/pages/user/liked-trainer.tsx
  src/types/chat.ts
  src/types/quote.ts
  src/types/reviews.ts
Labels: 완료, 기능 구현

#136 [서유림] Feat: 전체 UI 및 기능 수정
  src/components/Cards/MyReviewCard.tsx
  src/components/Cards/RequestLessonCard.tsx
  src/components/Cards/UserCard.tsx
  src/components/Common/Title.tsx
  src/components/CreateRequest/ChatBubble.tsx
  src/components/DetailTrainer/TrainerControl.tsx
  src/components/Modal/ModalContainer.tsx
  src/lib/api/lessonService.ts
  src/lib/api/queries/lesson.ts
  src/pages/trainer/managing-request/rejected-request.tsx
  src/pages/trainer/managing-request/sent-request/[id].tsx
  src/pages/trainer/managing-request/sent-request/index.tsx
  src/pages/trainer/received-request.tsx
  src/pages/user/create-request.tsx
  src/pages/user/lesson-review/written-review.tsx
  src/pages/user/liked-trainer.tsx
  src/pages/user/my-lesson/lesson-history/index.tsx
  src/styles/globals.css
  src/types/lesson.ts
Labels: 완료, 기능 구현, UI 구현

#137 [천우승] FIX: 채팅 기능 수정
  src/components/Chat/ChatList.tsx
  src/components/Chat/ChatRoom.tsx
  src/components/Chat/Chatting.tsx
  src/components/Chat/InputField.tsx
  src/components/Chat/MessageContainer.tsx
  src/lib/api/chatService.ts
  src/pages/chat.tsx
  src/types/chat.ts
Labels: 완료, 기능 구현

#141 [서유림] Fix: 버그 수정
  src/assets/ic/ic_chat.svg
  src/components/Cards/PendingLessonCard.tsx
  src/components/Common/Title.tsx
  src/components/DetailTrainer/TrainerControl.tsx
  src/hooks/useQuoteValidate.ts
  src/imageExports.ts
  src/pages/trainer/received-request.tsx
  src/pages/user/create-request.tsx
  src/pages/user/find-trainer.tsx
  src/pages/user/my-lesson/past-lesson/[quoteId].tsx
  src/pages/user/my-lesson/pending-request/[quoteId].tsx
  src/pages/user/my-lesson/pending-request/index.tsx
  src/pages/user/profile/edit.tsx
  src/pages/user/profile/index.tsx
Labels: 완료

#143 [이강수] Feat: 프로필 등록 이후에 noti, 마이페이지 보이게 하기. setUser with hasProfile
  .github/workflows/main.yml
  src/components/Common/Favorite.tsx
  src/components/Common/Input.tsx
  src/components/GNB/GNB.tsx
  src/components/GNB/MyProfileMenus.tsx
  src/components/SignUp/SignUpForm.tsx
  src/contexts/UserProvider.tsx
  src/lib/api/chatbotService.ts
  src/lib/api/queries/user.ts
  src/pages/ai-chatbot.tsx
  src/pages/noti.tsx
  src/pages/query-params-test.tsx
  src/pages/sns-login.tsx
  src/pages/trainer/[trainerId]/profile/edit.tsx
  src/pages/trainer/[trainerId]/profile/regist.tsx
  src/pages/user/profile/edit.tsx
Labels: 완료

#142 [천우승] FIX: QA 사항 확인 후 수정
  src/components/Cards/RejectedRequestCard.tsx
  src/components/Chat/ChatList.tsx
  src/components/Chat/ChatRoom.tsx
  src/pages/chat.tsx
  src/pages/user/create-request.tsx
  src/types/chat.ts
  src/types/lesson.ts
Labels: 진행중, 기능 구현

#147 [서유림] Docs: README 작성
  README.md
Labels: 완료

#148 [천우승] FIX: 채팅 기능 수정
  src/components/Chat/ChatList.tsx
  src/lib/api/chatService.ts
  src/lib/utils/socket.ts
  src/pages/user/lesson-review/written-review.tsx
  src/pages/user/liked-trainer.tsx
Labels: 완료, 기능 구현

#145 [이강수] Feat: invalidateQueries "user-info" and "trainer-info", and page redirect
  .github/workflows/main.yml
  src/components/Common/Textarea.tsx
  src/components/GNB/GNB.tsx
  src/components/GNB/Menus.tsx
  src/components/GNB/MyProfileMenus.tsx
  src/components/Modal/ReviewModal.tsx
  src/components/SignUp/ImageUploader.tsx
  src/components/SignUp/SignUpForm.tsx
  src/contexts/UserProvider.tsx
  src/lib/api/chatbotService.ts
  src/lib/api/instance.ts
  src/lib/utils/RoleGuard.ts
  src/pages/ai-chatbot.tsx
  src/pages/login.tsx
  src/pages/sns-login.tsx
  src/pages/trainer/[trainerId]/profile/edit.tsx
  src/pages/trainer/[trainerId]/profile/index.tsx
  src/pages/trainer/[trainerId]/profile/regist.tsx
  src/pages/user/profile/edit.tsx
  src/pages/user/profile/index.tsx
  src/pages/user/profile/regist.tsx
  src/types/types.ts
Labels: 완료

#150 [서유림] Feat: 수정사항
  README.md
  src/components/Cards/RequestLessonCard.tsx
  src/pages/user/detail-trainer/[trainerId].tsx
Labels: 완료

#154 [서유림] Fix: 수정
  src/components/Cards/ActiveLessonCard.tsx
  src/components/Cards/FavoriteTrainerCard.tsx
  src/components/Cards/FindTrainerCard.tsx
  src/components/Cards/PendingLessonCard.tsx
  src/components/Cards/QuoteCard.tsx
  src/components/Cards/QuoteSummary.tsx
  src/components/Cards/RequestLessonCard.tsx
  src/components/Cards/SentRequestCard.tsx
  src/components/Common/Card/TrainerInfo/TrainerInfo.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/FindTrainer/FavoriteTrainer.tsx
  src/components/ReceivedRequest/ListHeader.tsx
  src/pages/index.tsx
  src/pages/trainer/received-request.tsx
  src/pages/user/find-trainer.tsx
  src/pages/user/my-lesson/lesson-history/index.tsx
Labels: 완료

#153 [이강수] Minor corrections
  src/components/GNB/GNB.tsx
  src/components/GNB/MyProfileMenus.tsx
  src/components/SignUp/SignUpForm.tsx
  src/pages/ai-chatbot.tsx
  src/pages/login.tsx
Labels: 완료

#156 [서유림] Fix: 정렬 및 이미지 수정
  src/components/Common/Card/TrainerInfo/TrainerInfo.tsx
  src/components/Dropdown/Dropdown.tsx
Labels: 완료

#158 [이강수] Feat: chat scrollTop to bottom
  src/pages/ai-chatbot.tsx
Labels: 완료

#161 [서유림] Fix: 모바일 필터 오류
  src/components/CheckboxFilter.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/ReceivedRequest/LessonFilter.tsx
  src/components/ReceivedRequest/ListHeader.tsx
  src/pages/trainer/received-request.tsx
Labels: 완료

#164 [이강수] Feat: ai-chat scrollTo bottom
  src/pages/ai-chatbot.tsx
Labels: 완료

#167 [이강수] Update [quoteId].tsx
  src/pages/user/my-lesson/past-lesson/[quoteId].tsx
  src/types/types.ts
Labels: 완료
